### ISSUE TITLE
Login options not working

### ISSUE THREAD

**Issue by perc1million** [Lattyware/manydecks#16]
Not sure how else to put it; I've tried both login options but I do not appear to be signed in. Back to back, I can try the options because neither of them log me in. Idk if it's because I've never had ann account on this service prior to the bug? Are returning users still logging in? 

1. Click sign in
2. Choose option
3. Select credentials, allow access
4. repeat steps 2-3 ad infinitum

Can't upload screenshots

**Comment by Lattyware** [comment]
Hrm, have you tried disabling ad blockers or anti-tracking plugins/browser settings? I know for a fact that Google's sign in can play up if certain things are blocked.

Checking for myself, I can't seem to sign in with Twitch, but Google is working. I'll take a look and try to find out what is up with the twitch sign in option ASAP.

**Comment by perc1million** [comment]
Okay, I think I figured it out; I have to allow cookies from all sites. Thanks

**Comment by SirMangler** [comment]
I have this problem using Firefox and Twitch Sign-In. I have disabled all adblockers and even disabled firefox's "Advanced Tracking Protection". 

It redirects me to twitch, I hit authorise, and am returned to the site not logged in. Twitch emailed me stating it authorised a login, so it's working on Twitch's end.

**Comment by Lattyware** [comment]
Yeah, I believe the Twitch login is broken at the moment. I'll take a look as soon as I get a chance.
