### ISSUE TITLE
Support print-on-demand

### ISSUE THREAD

**Issue by dragonpaw** [Lattyware/manydecks#45]
Under cardcast, you could order a physical copy of your cards printed by one of the online POD houses. Great for taking a deck you'd worked on online and using it for at-home play.

**Comment by UnDeadPat** [comment]
That's what killed CardCast. Cards Against Humanity (the company) are pretty strict when it comes to printing.

**Comment by Lattyware** [comment]
Yeah, this is very much out of scope for the project. If someone would like to consume our API and write a service they are welcome to do so, but it's not something that we'll be implementing into many decks itself.

**Comment by dragonpaw** [comment]
> That's what killed CardCast. Cards Against Humanity (the company) are pretty strict when it comes to printing.

I'm really confused as to why you would say this. Do you have some insider knowledge of what happened with CardCast?

Printing cards that are compatible with the idea of CAH is absolutely legal under US copyright law, and protected up to and including a couple of Supreme Court cases. There's dozens of quite profitable compatible expansions for sale on numerous sites and on Amazon. The only requirements is to not use the CAH name, logos, or text. So the backs have to be something like 'My Cards' and maybe if you're paranoid don't use the same black/white scheme and font. But as long as the cards are not confusingly similar looking, and clearly different that official cards, there's absolutely no law in the land that you could be in trouble with, and in fact a great many protecting you.

**Comment by UnDeadPat** [comment]
"Sir, this is a GitHub"

**Comment by dragonpaw** [comment]
> "Sir, this is a GitHub"

True, but it's still good to fight misinformation on the Internet.

**Comment by UnDeadPat** [comment]
> misinformation 

k

**Comment by Lattyware** [comment]
There is no need for this here. Of course printing cards is not inherently breaking copyright, but people *can* use it to try and print copies of copyrighted decks. Either way, it is out of scope for Many Decks.
