### ISSUE TITLE
google sign in broken

### ISSUE THREAD

**Issue by boneso1dier** [Lattyware/manydecks#47]
## Describe the bug
Signing in with google does not work. 

## How to reproduce the bug
Steps to reproduce the behaviour:
1. Go to https://decks.rereadgames.com/sign-in
2. Click sign in with google
3. Pop up should say "Error 401: deleted_client The OAuth client was deleted."

### Expected behaviour
This is supposed to open a page where you select which email you want to use to sign in. 

### Attachments
![googlebroken](https://user-images.githubusercontent.com/91928048/135949864-ba3a3c59-9e94-40f0-9727-82f4b13228d4.JPG)

**Comment by TheNightling** [comment]
I'm having the same exact problem.  In fact I created this account just to report it.

**Comment by Lattyware** [comment]
Apologies, the google credential expired. I've recreated it and the log in seems to be working again. I'll close this as solved, but please do open a new issue if you run into further problems.
