### ISSUE TITLE
Error after deleting deck.

### ISSUE THREAD

**Issue by CookieCoder15** [Lattyware/manydecks#5]
I get an error after deleting a deck. The deck does get deleted but right after deleting, the background turns red and it says "Sorry, there appears to have been a problem, please try refreshing the page. Unable to decode the response from the server: Problem with the given value: {} Expecting a STRING"

I have tested this on both empty decks and ones containing a few cards, I get the error regardless.

**Comment by CookieCoder15** [comment]
Also after dismissing the error, I am not redirected and am shown a blank screen.

**Comment by Lattyware** [comment]
Yeah, there is a bug here with how we handle the response from the server and redirection.
