### ISSUE TITLE
Public Decks and Searching Feature

### ISSUE THREAD

**Issue by CookieCoder15** [Lattyware/manydecks#6]
Feature request for public decks so that users can make and share decks with everyone. A rating and search system would be good as well so that users can sort by most played/liked and search by keywords.

**Comment by Lattyware** [comment]
Yeah, this would definitely be nice to start properly replacing Cardcast.

As of the latest update, you can link people directly to decks to view them, at least.

**Comment by Lattyware** [comment]
This has now been added, in a basic form (listed decks, and browsing/searching them).
