### ISSUE TITLE
Twitch & Google sign in both non functional

### ISSUE THREAD

**Issue by GeneralNuisance0** [Lattyware/manydecks#79]
## Describe the bug
Please copy and paste or screenshot any error you received.

## How to reproduce the bug
Steps to reproduce the behaviour:
1. Sign in
2. Go to the decks page
3. …

### Attachments
If you—for example—uploaded a deck, and it went wrong, please attach the .deck.json5 file here.

**Comment by Lattyware** [comment]
Should be fixed, was an issue with a new deployment environment, in testing I can log in with both. Please reopen this or open a new issue if the problem persists.
